;; Generated by :claw at 2021-04-20T00:17:12.884746+03:00
(asdf:defsystem #:claw-usb-bindings
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))